from __future__ import annotations

from types import TracebackType
from typing import Any, Literal, Mapping, Sequence

Vector = Sequence[float | int]
DType = Literal["f32", "f16", "u64"]
SyncMode = Literal["full", "normal", "off"]
AccessMode = Literal["read_write", "read_only", "immutable"]
MissingIndexPolicy = Literal["fallback", "build_in_memory", "error"]
EdgeDirection = Literal["out", "in", "both"]
Payload = Any

class ReadOnlyError(RuntimeError): ...
class RecoveryRequiredError(RuntimeError): ...
class ImmutableArtifactError(RuntimeError): ...
class GenerationBusyError(RuntimeError): ...
class UnsupportedDatabaseVersionError(RuntimeError): ...

class SearchHit:
    id: int
    score: float
    payload: Payload

class GroupedSearchResult:
    semantic_hits: list[SearchHit]
    graph_hits: list[SearchHit]

class ReachabilityStep:
    from_id: int
    to_id: int
    label: str

class ReachabilityResult:
    source_id: int
    target_id: int
    depth: int
    path: list[int]
    steps: list[ReachabilityStep]

class Edge:
    target_id: int
    label: str
    weight: float

class IncomingEdge:
    source_id: int
    target_id: int
    label: str
    weight: float

class NodeView:
    id: int
    vector: list[float | int]
    payload: Payload
    edges: list[Edge]
    num_edges: int

class QueryRow:
    row: dict[str, Any]

class HookContext:
    timings: dict[str, float]
    counts: dict[str, int]
    custom_data: dict[str, Any]
    observations: dict[str, float]
    aborted: bool

class Transaction:
    def insert(self, vector: Vector, payload: Payload = ...) -> None: ...
    def insert_with_id(self, id: int, vector: Vector, payload: Payload = ...) -> None: ...
    def link(self, src: int, dst: int, label: str = ..., weight: float = ...) -> None: ...
    def delete(self, id: int) -> None: ...
    def unlink(self, src: int, dst: int, label: str | None = ...) -> None: ...
    def update_payload(self, id: int, payload: Payload) -> None: ...
    def update_vector(self, id: int, vector: Sequence[float]) -> None: ...
    def pending_count(self) -> int: ...
    def commit(self) -> list[int]: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> Transaction: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> bool: ...

class TriviumDB:
    dtype: str
    def __init__(self, path: str, dim: int = ..., dtype: DType = ..., sync_mode: SyncMode = ..., load_text_index: bool = ..., auto_build_quiver: bool = ..., expected_nodes: int | None = ..., memory_limit_mb: int = ..., access_mode: AccessMode = ..., missing_index_policy: MissingIndexPolicy = ...) -> None: ...
    def insert(self, vector: Vector, payload: Payload = ...) -> int: ...
    def insert_with_id(self, id: int, vector: Vector, payload: Payload = ...) -> None: ...
    def batch_insert(self, vectors: Sequence[Vector], payloads: Sequence[Payload]) -> list[int]: ...
    def batch_insert_with_ids(self, ids: Sequence[int], vectors: Sequence[Vector], payloads: Sequence[Payload]) -> None: ...
    def delete(self, id: int) -> None: ...
    def update_payload(self, id: int, payload: Payload) -> None: ...
    def patch_payload(self, id: int, patch: Mapping[str, Any]) -> None: ...
    def update_vector(self, vector: Vector, id: int) -> None: ...
    def link(self, src: int, dst: int, label: str = ..., weight: float = ...) -> None: ...
    def unlink(self, src: int, dst: int, label: str | None = ...) -> None: ...
    def get(self, id: int) -> NodeView | None: ...
    def get_payload(self, id: int) -> Payload | None: ...
    def get_edges(self, id: int) -> list[Edge]: ...
    def get_incoming_edges(self, id: int, label: str | None = ...) -> list[IncomingEdge]: ...
    def neighbors(self, id: int, depth: int = ..., labels: Sequence[str] | None = ...) -> list[int]: ...
    def reachable(self, id: int, min_depth: int = ..., max_depth: int = ..., labels: Sequence[str] | None = ..., direction: Literal["outgoing", "incoming", "both"] = ..., max_visited_nodes: int = ...) -> list[ReachabilityResult]: ...
    def search(self, query_vector: Vector, top_k: int = ..., recall_k: int = ..., rerank_k: int = ..., expand_depth: int = ..., min_score: float = ..., payload_filter: Mapping[str, Any] | None = ..., max_edges_per_node: int = ..., min_edge_weight: float = ..., edge_direction: EdgeDirection = ...) -> list[SearchHit]: ...
    def search_grouped(self, query_vector: Vector, top_k: int = ..., recall_k: int = ..., rerank_k: int = ..., expand_depth: int = ..., min_score: float = ..., payload_filter: Mapping[str, Any] | None = ..., max_edges_per_node: int = ..., min_edge_weight: float = ..., edge_direction: EdgeDirection = ...) -> GroupedSearchResult: ...
    def search_advanced(self, query_vector: Vector, top_k: int = ..., recall_k: int = ..., rerank_k: int = ..., expand_depth: int = ..., min_score: float = ..., teleport_alpha: float = ..., enable_advanced_pipeline: bool = ..., enable_sparse_residual: bool = ..., fista_lambda: float = ..., fista_threshold: float = ..., enable_dpp: bool = ..., dpp_quality_weight: float = ..., enable_refractory_fatigue: bool = ..., enable_text_hybrid_search: bool = ..., text_boost: float = ..., custom_query_text: str | None = ..., payload_filter: Mapping[str, Any] | None = ..., force_brute_force: bool = ..., expand_labels: Sequence[str] | None = ..., max_edges_per_node: int = ..., min_edge_weight: float = ..., edge_direction: EdgeDirection = ...) -> list[SearchHit]: ...
    def search_hybrid(self, query_text: str | None = ..., query_vector: Vector | None = ..., top_k: int = ..., expand_depth: int = ..., min_score: float = ...) -> list[SearchHit]: ...
    def search_exact(self, query_vector: Vector, top_k: int) -> list[SearchHit]: ...
    def search_graph_first(self, query_vector: Vector, anchor_ids: Sequence[int], top_k: int, max_anchor_nodes: int = ...) -> list[SearchHit]: ...
    def search_batch(self, query_vectors: Sequence[Vector], top_k: int = ..., parallelism: int = ...) -> list[list[SearchHit]]: ...
    def search_with_context(self, query_vector: Vector, top_k: int = ..., custom_query_text: str | None = ...) -> tuple[list[SearchHit], HookContext]: ...
    def index_text(self, id: int, text: str) -> None: ...
    def index_keyword(self, id: int, keyword: str) -> None: ...
    def build_text_index(self) -> None: ...
    def create_index(self, field: str) -> None: ...
    def drop_index(self, field: str) -> None: ...
    def tql(self, query: str) -> list[QueryRow]: ...
    def tql_mut(self, query: str) -> dict[str, Any]: ...
    def transaction(self) -> Transaction: ...
    def leiden_cluster(self, resolution: float = ..., min_community_size: int = ..., max_iterations: int = ..., seed: int = ...) -> dict[str, Any]: ...
    def publish_generation_manifest(self, generation_id: str) -> dict[str, Any]: ...
    def migrate(self, new_path: str, new_dim: int) -> list[int]: ...
    def node_count(self) -> int: ...
    def dim(self) -> int: ...
    def all_node_ids(self) -> list[int]: ...
    def reserve_nodes(self, additional: int) -> None: ...
    def estimated_memory(self) -> int: ...
    def set_memory_limit(self, mb: int = ...) -> None: ...
    def set_sync_mode(self, mode: SyncMode) -> None: ...
    def set_auto_build_quiver(self, enabled: bool) -> None: ...
    def enable_auto_compaction(self, interval_secs: int = ...) -> None: ...
    def disable_auto_compaction(self) -> None: ...
    def clear_search_state(self) -> None: ...
    def compact(self) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def load_ffi_hook(self, lib_path: str) -> None: ...
    def clear_hook(self) -> None: ...
    def set_hook(self, hook: Any) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, id: int) -> bool: ...
    def __enter__(self) -> TriviumDB: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> bool: ...

def init_logger() -> None: ...
